language: ruby
rvm:
  - 2.0.0-p353
bundler_args: --without production
before_install:
  - gem update --system
  - gem --version
script:
  - bundle exec rake db:drop db:create db:migrate
  - bundle exec rspec spec
